apiVersion: v1
kind: Service
metadata:
  name: todos-service
  namespace: jsanchez
spec:
  type: NodePort
  selector:
    app: todos-api
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080