apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-deployment
  namespace: jsanchez
  labels:
    app: todos-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
        - name: todos-api
          image: sjulian/todolist-api:local
          ports:
            - containerPort: 8080